In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import scipy
import statsmodels.api as sm

In [27]:
try:
    path = "C:\\Users\\mayan\\Downloads\\WA_Fn-UseC_-HR-Employee-Attrition.csv"
    df = pd.read_csv(path)
except Exception as e :
    print(f"Data can't be loaded. error :{e}")

In [28]:
df.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

In [29]:
df.describe()

Age    DailyRate  DistanceFromHome    Education  EmployeeCount  \
count  1470.000000  1470.000000       1470.000000  1470.000000         1470.0   
mean     36.923810   802.485714          9.192517     2.912925            1.0   
std       9.135373   403.509100          8.106864     1.024165            0.0   
min      18.000000   102.000000          1.000000     1.000000            1.0   
25%      30.000000   465.000000          2.000000     2.000000            1.0   
50%      36.000000   802.000000          7.000000     3.000000            1.0   
75%      43.000000  1157.000000         14.000000     4.000000            1.0   
max      60.000000  1499.000000         29.000000     5.000000            1.0   

       EmployeeNumber  EnvironmentSatisfaction   HourlyRate  JobInvolvement  \
count     1470.000000              1470.000000  1470.000000     1470.000000   
mean      1024.865306                 2.721769    65.891156        2.729932   
std        602.024335                 1.093082    20.329428        0.711561   
min          1.000000                 1.000000    30.000000        1.000000   
25%        491.250000                 2.000000    48.000000        2.000000   
50%       1020.500000                 3.000000    66.000000        3.000000   
75%       1555.750000                 4.000000    83.750000        3.000000   
max       2068.000000                 4.000000   100.000000        4.000000   

          JobLevel  ...  RelationshipSatisfaction  StandardHours  \
count  1470.000000  ...               1470.000000         1470.0   
mean      2.063946  ...                  2.712245           80.0   
std       1.106940  ...                  1.081209            0.0   
min       1.000000  ...                  1.000000           80.0   
25%       1.000000  ...                  2.000000           80.0   
50%       2.000000  ...                  3.000000           80.0   
75%       3.000000  ...                  4.000000           80.0   
max       5.000000  ...                  4.000000           80.0   

       StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
count       1470.000000        1470.000000            1470.000000   
mean           0.793878          11.279592               2.799320   
std            0.852077           7.780782               1.289271   
min            0.000000           0.000000               0.000000   
25%            0.000000           6.000000               2.000000   
50%            1.000000          10.000000               3.000000   
75%            1.000000          15.000000               3.000000   
max            3.000000          40.000000               6.000000   

       WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
count      1470.000000     1470.000000         1470.000000   
mean          2.761224        7.008163            4.229252   
std           0.706476        6.126525            3.623137   
min           1.000000        0.000000            0.000000   
25%           2.000000        3.000000            2.000000   
50%           3.000000        5.000000            3.000000   
75%           3.000000        9.000000            7.000000   
max           4.000000       40.000000           18.000000   

       YearsSinceLastPromotion  YearsWithCurrManager  
count              1470.000000           1470.000000  
mean                  2.187755              4.123129  
std                   3.222430              3.568136  
min                   0.000000              0.000000  
25%                   0.000000              2.000000  
50%                   1.000000              3.000000  
75%                   3.000000              7.000000  
max                  15.000000             17.000000  

[8 rows x 26 columns]

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64 
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64 
 6   Education                 1470 non-null   int64 
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64 
 9   EmployeeNumber            1470 non-null   int64 
 10  EnvironmentSatisfaction   1470 non-null   int64 
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64 
 13  JobInvolvement            1470 non-null   int64 
 14  JobLevel                

In [31]:
print(f"There are {df.isnull().sum().sum()} null values in the dataset.\nThere are {df.duplicated().sum()} duplicates in the dataset.")

There are 0 null values in the dataset.
There are 0 duplicates in the dataset.


In [32]:
df.columns = df.columns.str.lower()

In [34]:
def Info():
    total_drops = 0
    for col in df.columns:
        if df[col].nunique() < 10:
            print(df[col].name)
            print(df[col].unique())
            if df[col].nunique() <= 1:
                total_drops += 1
                print(f"Removing {col} from the data frame.")
                df.drop(columns=col, inplace= True)

    print(f"total droped col = {total_drops}")
                

Info()

attrition
['Yes' 'No']
businesstravel
['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']
department
['Sales' 'Research & Development' 'Human Resources']
education
[2 1 4 3 5]
educationfield
['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']
employeecount
[1]
Removing employeecount from the data frame.
environmentsatisfaction
[2 3 4 1]
gender
['Female' 'Male']
jobinvolvement
[3 2 4 1]
joblevel
[2 1 3 4 5]
jobrole
['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']
jobsatisfaction
[4 2 3 1]
maritalstatus
['Single' 'Married' 'Divorced']
over18
['Y']
Removing over18 from the data frame.
overtime
['Yes' 'No']
performancerating
[3 4]
relationshipsatisfaction
[1 4 2 3]
standardhours
[80]
Removing standardhours from the data frame.
stockoptionlevel
[0 1 3 2]
trainingtimeslastyear
[0 3 2 5 1 4 6]
worklifebalance
[1 3 2 4]
t

In [35]:
df.sample(5)

age attrition businesstravel  dailyrate              department  \
559    38        No  Travel_Rarely        268  Research & Development   
496    21        No  Travel_Rarely       1343                   Sales   
238    32        No  Travel_Rarely       1401                   Sales   
1402   31        No  Travel_Rarely       1276  Research & Development   
808    29        No  Travel_Rarely       1107  Research & Development   

      distancefromhome  education    educationfield  employeenumber  \
559                  2          5           Medical             773   
496                 22          1  Technical Degree             669   
238                  4          2     Life Sciences             330   
1402                 2          1           Medical            1974   
808                 28          4     Life Sciences            1120   

      environmentsatisfaction  ... performancerating  \
559                         4  ...                 3   
496                         3  ...                 3   
238                         3  ...                 3   
1402                        4  ...                 3   
808                         3  ...                 4   

      relationshipsatisfaction  stockoptionlevel  totalworkingyears  \
559                          2                 1                  6   
496                          3                 0                  3   
238                          1                 1                  6   
1402                         3                 3                  1   
808                          1                 1                 11   

     trainingtimeslastyear  worklifebalance yearsatcompany  \
559                      0                1              1   
496                      2                3              3   
238                      5                3              4   
1402                     4                3              1   
808                      1                3              7   

      yearsincurrentrole  yearssincelastpromotion  yearswithcurrmanager  
559                    0                        0                     1  
496                    2                        1                     2  
238                    3                        1                     2  
1402                   0                        0                     0  
808                    5                        1                     7  

[5 rows x 32 columns]

In [36]:
df.to_csv("hr_manages.csv", index= True)